### ISSUE TITLE
Random value: limitation to 24 hours

### ISSUE THREAD

**Issue by chrisbn** [cabforum/smime#117]
Section 3.2.2.2 Validating control over mailbox via email states "The Random Value SHALL be unique in each email. The Random Value SHALL remain valid for use in a confirming response for no more than 24 hours from its creation. The CA MAY specify a shorter validity period for Random Values in its CP and/or CPS."

In the TLS BRs, the random value may remain valid for no more than 30 days from its creation: "The Random Value SHALL remain valid for use in a confirming response for no more than 30 days from its creation. The CPS MAY specify a shorter validity period for
Random Values, in which case the CA MUST follow its CPS."

Could this value be aligned to 30 days between TLS BRs and SMIME BRs? Is there a specific driver aiming to reduce this value for SMIME?

**Comment by cairnsc** [comment]
We hope this change to reduce the lifetime will improve security and influence change within the SCGW’s validation subcommittee but the two changes will have to happen asynchronously since updating the BRs is a separate effort that would take time. Do you have a use case that would require the random value to have a longer validity period than 24 hours?

Since validation of control via email is a near-immediate validation method, we believe that a value does not need to be greater than 24 hours and exposes users to risk. A new random value could be requested if the user fails to use it within that period. As a point of comparison, NIST SP800-63A Identity Assurance Level 2 (IAL2), section 4.4.1.6 (5) (e) specifies that remote unsupervised proofing of email addresses shall be implemented with an enrollment code having a maximum validity period of 24 hours. We believe this provides a good balance of avoiding misuse while ensuring usability.

Thanks,
Google Trust Services team

**Comment by srdavidson** [comment]
Does this work better?

The Random Value SHALL be reset upon each instance of the email sent by the CA to a Mailbox Address, however all relevant Random Values sent to that Mailbox Address SHALL remain valid for use in a confirming response within the validity period described in this Section. In addition, the Random Value SHALL be reset upon first use by the user if intended for additional use as an authentication factor following the Mailbox Address verification.

**Comment by vanbroup** [comment]
> all relevant Random Values sent to that Mailbox Address SHALL remain valid for use in a confirming response within the validity period

Should this SHALL be a MAY instead?

The current language reads as if all random values must be usable until they are expired or used, which could make sense from a user experience point of view but I don't think we agreed that this should be a requirement. There might be a reason to revoke a random value.

**Comment by srdavidson** [comment]
Agreed; willfix.
