### ISSUE TITLE
Subscriber Certificates Do we need LDAP and FTP References for SMIME BR

### ISSUE THREAD

**Issue by AshishGlobalSign** [cabforum/smime#132]
Current Text : Refer at 7.1.2.3 This extension SHALL NOT be marked critical, and it SHALL contain at least one accessMethod value of type id-ad-ocsp that specifies the HTTP URI of the Issuing CA's OCSP responder. For Legacy profiles only, additional publicly accessible id-ad-ocsp LDAP, FTP, or HTTP URIs MAY be specified.

Question : AIA.ocsp of LDAP and FTP shall be removed in this profile since they are not so common and I never see them. Further more FTP is not described in RFC 6960 OCSP as a protocol example.
So, just wanted to understand it references from where it is coming here ? and do we need it

**Comment by XolphinMartijn** [comment]
I believe the idea here is to phase them out over time for any CA that might use this. The language only allows LDAP and FTP OCSP responder URLs for legacy profiles. This implies it MUST NOT be included in Multipurpose and Strict profiles. 

Legacy profiles will be removed in a future version of the SMIME BRs, which means at that point it will no longer be allowed at all.

I do wonder if using LDAP OCSP would be a violation of 4.9.10: "OCSP responders operated by the CA SHALL support the HTTP GET method"
Even if both an HTTP and LDAP URL are included, would a different OCSP URL be considered a different responder, violating the HTTP GET requirement?

**Comment by CBonnell** [comment]
> I believe the idea here is to phase them out over time for any CA that might use this. The language only allows LDAP and FTP OCSP responder URLs for legacy profiles. This implies it MUST NOT be included in Multipurpose and Strict profiles.

Yes, the intent of the language is to allow LDAP/FTP for Legacy, since these protocols are used today. However, many clients only support HTTP, so it would be better from an interoperability standpoint to only allow HTTP in the long term.

> I do wonder if using LDAP OCSP would be a violation of 4.9.10: "OCSP responders operated by the CA SHALL support the HTTP GET method"
Even if both an HTTP and LDAP URL are included, would a different OCSP URL be considered a different responder, violating the HTTP GET requirement?

My understanding is that OCSP responders are identified by Name or KeyHash, not URI. As long as the CA provides an OCSP responder service operating at the specified HTTP URI that is authoritative for the certificate in question, then I don't see an issue with operating additional OCSP-based services and providing references to these service URIs in the AIA extension.
