### ISSUE TITLE
7.1.2.3 : cRLDistributionPoints in Subscriber Certificates

### ISSUE THREAD

**Issue by AshishGlobalSign** [cabforum/smime#137]
Current Text : cRLDistributionPoints (SHALL be present)

This extension SHOULD NOT be marked critical. It SHALL contain at least one distributionPoint whose fullName value includes a GeneralName of type uniformResourceIdentifier that includes a HTTP URI where the Issuing CA's CRL can be retrieved. For Legacy profiles only, additional publicly accessible fullName LDAP, FTP, or HTTP URIs MAY be specified.

Question : I think cRLDistributionPoints shall be optional and not most, the reason I am stating is "CRL for EE will have huge sige, CRL for subscriber certificates will become huge size and cRLDistributionPoints may be omitted like public TLS server certificates. Thus, cRLDistributionPoints extension shall be optional and recommended to use OCSP" ? Lets us know your thoughts

**Comment by CBonnell** [comment]
> Thus, cRLDistributionPoints extension shall be optional

I think I agree with this suggested change. As far as I'm aware, there is no Root Program policy mandating the inclusion of the CRLDP extension in end-entity Certificates, whereas there is at least one Root Program (namely, MSFT) that does mandate the inclusion of AIA OCSP. Given this, I think we can relax this requirement to make CRLDP optional.

**Comment by XolphinMartijn** [comment]
+1 as stated in issue https://github.com/cabforum/smime/issues/95#issuecomment-1137006826

**Comment by srdavidson** [comment]
I think Martijn's text moves in the agreed direction.  The AIA language may need to be changed as currently it requires the inclusion of an OCSP pointer in all cases – even when the CRLDP is present. We need to consider how to craft language so that a CA can include the CRLDP extension and solely the CA Issuers AIA pointer in a certificate. @XolphinMartijn want to make a try?
The goal would be to have a draft that we can share with Certificate Issuers to confirm the acceptability of the "either CRL or OCSP" or "both CRL or OCSP" options.

**Comment by XolphinMartijn** [comment]
Yea. I see the error in my original draft that would in not allow AIA-CA Issuers without OCSP. Working on a new one

**Comment by XolphinMartijn** [comment]
PR #140 added as proposal
