### ISSUE TITLE
Add linting requirements to S/MIME BR

### ISSUE THREAD

**Issue by srdavidson** [cabforum/smime#212]
Pointing out a corresponding thread at TLS BR https://github.com/cabforum/servercert/issues/443

As the implementation of the S/MIME BR matures, we might consider requirements for linting along the lines of:
- what should be linted
- how linting should be performed
- when linting should occur

**Comment by robplee** [comment]
I think this seems like a good idea in theory, but might have some issues in practice.  The main concern I have is that the linting ecosystem for SMIME certificates is nowhere near as mature for SMIME certs as it is for TLS.  Support for the SMIME BRs in zlint is barely there as there's just one lint merged so far and many more still needed.  AFAIK, there's just the new and shiny Digicert pkilint tool that really enforces the SMIME BRs effectively so I think it's much less reasonable for the SMIME BRs to require linting than it would be for the Server Cert BRs.

**Comment by bcmorton** [comment]
I also agree that required linting for S/MIME is too soon. In fact, I am not sure that required linting would make any improvements. The reason is that we would provide a requirement, then hope that linter(s) would be available and be maintained. We have seen that there are already old TLS linters no longer maintained. I'm hoping that CAs will lint S/MIME certificates and will help support and improve the linters. As the S/MIME BRs mature and the linters improve, then we can consider requiring linting.

**Comment by srdavidson** [comment]
Note that the ServerCert WG have passed a ballot to require pre-issuance linting of TLS.
https://cabforum.org/2024/06/27/ballot-sc-75-pre-sign-linting/
May be "a good time" to look at this again for S/MIME?

**Comment by srdavidson** [comment]
Draft might look something like this: https://github.com/srdavidson/smime/compare/927a78831c9330fe7c36d4a484c9eeed801c9c9d...09b8abf409966fb9cc64953ff1c7638af65deeb3
