### ISSUE TITLE
Clarify private key delivery to subscriber

### ISSUE THREAD

**Issue by srdavidson** [cabforum/smime#234]
The text in section 6.1.2 has been queried a number of times by both Certificate Issuers and Auditors seeking clarity.

The existing text was derived from the CSBR and edited for the S/MIME use.  In the process, requirements that belonged together (relating to hardware distribution) became separated. In addition it is unclear whether the "examples" are informative and address the common API method of delivery.

**Comment by srdavidson** [comment]
Proposed text improvement at https://github.com/srdavidson/smime/commit/cc22fd84788a6e8b502ca521b42dcb6757c6ecc2

**Comment by srdavidson** [comment]
Edits implementing the discussion in SMCWG: https://github.com/srdavidson/smime/commit/ae5a5daa46483d70b8b089fc9d778f17d64ba02f

**Comment by defacto64** [comment]
Stephen,

going back to what was discussed in yesterday's call: if anybody is considering whether or not to make some changes to the PKCS12 encryption algorithms, I recommend proceeding with **great caution** as, in our experience and as corroborated by various sources, **AES is not currently supported by macOS for PKCS12 files**. 

In practice, if you try to import a PKCS12 file encrypted with AES into the Mac's **KeyChain**, you get an error (and a misleading one at that). According to our tests, this problem is also present in the most recent versions of Apple maOS. So if anyone is thinking about imposing AES, I recommend holding off. 

To date, the only reasonably secure algorithm that is supported by all major platforms is 3DES-CBC. Although it is deprecated by NIST, I think there are no alternatives for now.

**Comment by CBonnell** [comment]
I agree with @defacto64 that 3DES is the only interoperable encryption algorithm currently. There was extensive discussion on the LAMPS mailing list on this topic when the PKCS12 examples in RFC 9216 were being created: https://mailarchive.ietf.org/arch/msg/spasm/Cl5LGMsvKDBTdkHA2VoL5FADzd0/.
